spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:tcp://localhost:1521/payment
    username: song
    password: song1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: song-group
      auto-offset-reset: earliest

logging:
  level:
    root: info
    song.pg.payment: debug

jwt:
  secret: song

grpc:
  client:
    token:
      address: static://127.0.0.1:50051
      negotiation-type: plaintext
